1.Import Required Libararies

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

2.Create a Sample Dataset

In [2]:
data = {
    'Age': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    'Study Hours': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    'Attendance': [60, 65, 70, 75, 80, 82, 85, 90, 92, 95],
    'Result': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
print('Dataset:')
display(df)

Dataset:

   Age  Study Hours  Attendance  Result
0   20            2          60       0
1   21            3          65       0
2   22            4          70       0
3   23            5          75       0
4   24            6          80       1
5   25            7          82       1
6   26            8          85       1
7   27            9          90       1
8   28           10          92       1
9   29           11          95       1

3.Separate Features and Target

In [3]:
X = df[['Age', 'Study Hours', 'Attendance']]
y = df['Result']

print('Features:')
display(X)

print('Target:')
display(y)

Features:

   Age  Study Hours  Attendance
0   20            2          60
1   21            3          65
2   22            4          70
3   23            5          75
4   24            6          80
5   25            7          82
6   26            8          85
7   27            9          90
8   28           10          92
9   29           11          95

Target:

0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    1
9    1
Name: Result, dtype: int64

4.Split data into training and testing instances

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)

print('Number of training instances:', len(X_train))
print('Number of testing instances:', len(X_test))

print('\nTraining Data:')
display(X_train.assign(Result=y_train))

print('\nTesting Data:')
display(X_test.assign(Result=y_test))

Number of training instances: 7
Number of testing instances: 3

Training Data:

   Age  Study Hours  Attendance  Result
5   25            7          82       1
3   23            5          75       0
1   21            3          65       0
7   27            9          90       1
9   29           11          95       1
4   24            6          80       1
0   20            2          60       0

Testing Data:

   Age  Study Hours  Attendance  Result
2   22            4          70       0
8   28           10          92       1
6   26            8          85       1

5.Create and train the machine learning model

In [5]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print('Model training completed successfully.')

Model training completed successfully.

6.Test the Trained Model

In [6]:
y_pred = model.predict(X_test)

results = X_test.copy()
results['Actual_Result'] = y_test.values
results['Predicted_Result'] = y_pred

print('Actual vs Predicted Results:')
display(results)

Actual vs Predicted Results:

   Age  Study Hours  Attendance  Actual_Result  Predicted_Result
2   22            4          70              0                 0
8   28           10          92              1                 1
6   26            8          85              1                 1

7.Evaluate Model Performance

In [8]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

print('\nClassification Report:')
print(classification_report(y_test, y_pred, zero_division=0))

print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3


Confusion Matrix:
[[1 0]
 [0 2]]

8.Test a New Instance

In [15]:
new_instance = pd.DataFrame({
    'Age': [26],
    'Study Hours': [8],
    'Attendance': [88]
})

prediction = model.predict(new_instance)[0]
probability = model.predict_proba(new_instance)[0]

print('New Instance')
display(new_instance)

print('Predicted Result:', 'Pass' if prediction == 1 else 'Fail')
print('Prediction probabilities:', probability)

New Instance

   Age  Study Hours  Attendance
0   26            8          88

Predicted Result: Pass
Prediction probabilities: [2.15119873e-04 9.99784880e-01]